Complete Numpy 

import np as numpy

In [ ]:
import numpy as np
import time
a1 = np.arange(10)
print(a1)



[0 1 2 3 4 5 6 7 8 9]


In [14]:
a2 = np.arange(36).reshape(6 , 6)
a3 = np.arange(36).reshape(6 , 6)
a2
final = a2 + a3
print(final)

[[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]
 [24 26 28 30 32 34]
 [36 38 40 42 44 46]
 [48 50 52 54 56 58]
 [60 62 64 66 68 70]]


In [ ]:
a2
a3

In [21]:
A = np.arange(12).reshape(3, 2 , 2)
A

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [28]:
l1 = [i for i in range(100000000)]
l2 = [i for i in range(100000000, 200000000)]
import time
add = []
start = time.time()
for i in range(len(l1)):
    add.append(l1[i] + l2[i])
print(time.time()-start)

45.36348915100098


ghbbcxnxnmx

In [ ]:
l1 = np.arange(100000000)
l2 = np.arange(100000000, 200000000)
import time
add = []
start = time.time()
result = l1 + l2
print(time.time()-start)


0.3032948970794678


In [42]:
x = np.ones(12, dtype=str)
x

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
      dtype='<U1')

In [44]:
linear = np.linspace(-10 , 10 , 10)
linear

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [54]:
t = np.arange(12).reshape(3 , 4)
tt = t.astype(np.int8)
tt.itemsize


1

Array Operations

In [ ]:

# A1 = np.arange(12).reshape(3 , 4)
# x = 5
# A1 * x 


array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [64]:
A1 = np.arange(1, 5).reshape(2 , 2)
A2 = np.arange(5 , 9).reshape(2 , 2)
A1 * A2

array([[ 5, 12],
       [21, 32]])