In [3]:
import numpy as np

In [4]:
a1 = np.array([1, 2, 3])
a2 = np.array([5])                          

result = a1 + a2
result

d1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
d2 = np.array([10, 20, 30])
result2 = d1 + d2
result2

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [6]:
x = np.array([1, 2, 3])
y = 5
result = x * y
result


array([ 5, 10, 15])

In [21]:
data = np.random.randint(1, 30, size=(4, 4))
d2 = np.random.randint(1, 10, size=(1, 4))
result = data * d2
print("Array 1:\n", data)
print("\nArray 2:\n", d2)
print("\nBroadcasting result:\n", result)


Array 1:
 [[ 2 13 26  3]
 [ 9 23 14 20]
 [ 1  7 24 13]
 [26  9 16 25]]

Array 2:
 [[4 7 9 8]]

Broadcasting result:
 [[  8  91 234  24]
 [ 36 161 126 160]
 [  4  49 216 104]
 [104  63 144 200]]


In [25]:
a1 = np.random.randint(1, 10, size=(4,1))
a2 = np.random.randint(10,20, size=(1,3))
result = a1+a2
result

array([[18, 16, 19],
       [14, 12, 15],
       [20, 18, 21],
       [14, 12, 15]], dtype=int32)