In [32]:
import numpy as np

In [33]:
a= np.arange(1 ,11)
np.arange(1 , 11 , 2)
np.arange(1 , 11).reshape(2, 5)
np.arange(1, 25).reshape(4, 6)
np.zeros((3, 4))
np.ones((3, 4))
np.random.random((4 , 4))
np.linspace(-10, 10, 5)
a1 = np.identity(4)
a1.ndim


2

In [56]:
a2 = np.arange(1, 25).reshape(4, 6)
a3 = np.arange(1, 11)
# a3.shape[0]
a3.size
a3.itemsize
a3.dtype

a3.astype(np.int32)
a3.itemsize

# scalar operations
a4 = np.arange(1, 17).reshape(4, 4)
k = 4 # scalar operator
a4 * k


data = np.arange(1, 17).reshape(4, 4)
data >= 10
np.min(data, axis=1)

np.cos(a3)





array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [87]:
A = np.arange(1, 13).reshape(3, 4)
B = np.arange(1, 13).reshape(3, 4)
np.add(A, B)
np.subtract(A, B)
np.multiply(A, B)
np.dot(A, B.T)

x = np.arange(1 , 7, dtype=np.float64).reshape(2, 3)
y = np.arange(7 , 13, dtype=np.float64).reshape(3, 2)
np.dot(x, y)

np.log(x)
np.exp(x)

y


x1 = 0.6
np.round(x1)


np.float64(1.0)

In [129]:
d1 = np.arange(10)
d2 = np.arange(12).reshape(3, 4)
d3 = np.arange(8).reshape(2,2,2)
d1[-1]
d2[-1, -1]

d3[1, 1, 1]

# SLICING
d1[0: 5]
d2[0, 0:3]

d2[:1]


# for i in d2:
#     print(i)
    

# revel = d2.ravel()
# revel
transpose = d2.T
transpose


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [134]:
# # Horizontal stacking: joins arrays column-wise
# horizontal_stack = np.hstack((A, B))
# print("Horizontal stacking:\n", horizontal_stack)

# # Vertical stacking: joins arrays row-wise
# vertical_stack = np.vstack((A, B))
# print("\nVertical stacking:\n", vertical_stack)

X = np.arange(1, 13).reshape(3, 4)
Y = np.arange(13, 25).reshape(3, 4)

h_stack = np.hstack((X,Y))
print("Horizontal stacking:\n", h_stack)
v_stack = np.vstack((X,Y))
print("\nVertical stacking: \n", v_stack)

Horizontal stacking:
 [[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]

Vertical stacking: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [141]:

import time
import random
import numpy as np
 
 
def make_python_matrix(rows, cols):
    return [[random.random() for _ in range(cols)] for _ in range(rows)]
 
 
def python_matmul(A, B):
    rows_A, cols_A = len(A), len(A[0])
    rows_B, cols_B = len(B), len(B[0])
    result = [[0.0] * cols_B for _ in range(rows_A)]
    for i in range(rows_A):
        for j in range(cols_B):
            s = 0.0
            for k in range(cols_A):
                s += A[i][k] * B[k][j]
            result[i][j] = s
    return result
 
 
def python_elementwise_add(A, B):
    return [[A[i][j] + B[i][j] for j in range(len(A[0]))] for i in range(len(A))]
 
 
def python_elementwise_mul(A, B):
    return [[A[i][j] * B[i][j] for j in range(len(A[0]))] for i in range(len(A))]
 
 
def python_sum(A):
    total = 0.0
    for row in A:
        for val in row:
            total += val
    return total
 
 
def python_dot(a, b):
    return sum(x * y for x, y in zip(a, b))
 
 
def timed(func, *args, **kwargs):
    start = time.perf_counter()
    result = func(*args, **kwargs)
    end = time.perf_counter()
    return result, end - start
 
 
def compare_operation(name, python_time, numpy_time):
    speedup = python_time / numpy_time if numpy_time > 0 else float("inf")
    print(f"{name:<28} | Python: {python_time:>10.6f}s | NumPy: {numpy_time:>10.6f}s | Speedup: {speedup:>8.1f}x")



def run_comparison(n):
    print(f"\n{'='*90}")
    print(f"MATRIX SIZE: {n} x {n}")
    print(f"{'='*90}")
 
    # --- Setup ---
    A_py = make_python_matrix(n, n)
    B_py = make_python_matrix(n, n)
    A_np = np.array(A_py)
    B_np = np.array(B_py)
 
    vec_a_py = [random.random() for _ in range(n * n)]
    vec_b_py = [random.random() for _ in range(n * n)]
    vec_a_np = np.array(vec_a_py)
    vec_b_np = np.array(vec_b_py)
 
    # --- Matrix multiplication ---
    # NOTE: pure-python matmul is O(n^3) and gets very slow — skip for large n
    if n <= 200:
        _, t_py = timed(python_matmul, A_py, B_py)
    else:
        t_py = float("nan")
    _, t_np = timed(lambda: A_np @ B_np)
    compare_operation("Matrix Multiplication", t_py, t_np)
 
    # --- Element-wise addition ---
    _, t_py = timed(python_elementwise_add, A_py, B_py)
    _, t_np = timed(lambda: A_np + B_np)
    compare_operation("Element-wise Addition", t_py, t_np)
 
    # --- Element-wise multiplication ---
    _, t_py = timed(python_elementwise_mul, A_py, B_py)
    _, t_np = timed(lambda: A_np * B_np)
    compare_operation("Element-wise Multiplication", t_py, t_np)
 
    # --- Sum of all elements ---
    _, t_py = timed(python_sum, A_py)
    _, t_np = timed(lambda: A_np.sum())
    compare_operation("Sum of Elements", t_py, t_np)
 
    # --- Dot product (1D, size n*n) ---
    _, t_py = timed(python_dot, vec_a_py, vec_b_py)
    _, t_np = timed(lambda: np.dot(vec_a_np, vec_b_np))
    compare_operation("Dot Product (1D)", t_py, t_np)
    
    
if __name__ == "__main__":
    for size in [10, 100, 200, 500, 1000]:
        run_comparison(size)
        


MATRIX SIZE: 10 x 10
Matrix Multiplication        | Python:   0.000097s | NumPy:   0.000025s | Speedup:      3.9x
Element-wise Addition        | Python:   0.000013s | NumPy:   0.000004s | Speedup:      3.1x
Element-wise Multiplication  | Python:   0.000011s | NumPy:   0.000003s | Speedup:      3.8x
Sum of Elements              | Python:   0.000005s | NumPy:   0.000014s | Speedup:      0.4x
Dot Product (1D)             | Python:   0.000013s | NumPy:   0.000008s | Speedup:      1.7x

MATRIX SIZE: 100 x 100
Matrix Multiplication        | Python:   0.084799s | NumPy:   0.000145s | Speedup:    584.4x
Element-wise Addition        | Python:   0.000922s | NumPy:   0.000027s | Speedup:     34.5x
Element-wise Multiplication  | Python:   0.000894s | NumPy:   0.000029s | Speedup:     30.8x
Sum of Elements              | Python:   0.000336s | NumPy:   0.000042s | Speedup:      8.1x
Dot Product (1D)             | Python:   0.000803s | NumPy:   0.000029s | Speedup:     27.8x

MATRIX SIZE: 200 x 200


In [147]:
data = np.arange(4 , 20).reshape(4,4)
data

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [164]:
data[0, [0]]

array([4])

In [170]:
arr = np.random.randint(1,100, 24).reshape(6, 4)
arr > 20 # only Boolean values
arr[arr > 20] # values where condition is True
odds = arr[arr % 2 == 1]
print("\nOdd numbers in the array:\n", odds)
evens = arr[arr % 2 == 0]
print("\nEven numbers in the array:\n", evens)


Odd numbers in the array:
 [39 23 89 11 13 29 33 21 13 39 21 59]

Even numbers in the array:
 [20 62 84  4 34 72 42 18 10 70 92 82]
